version: '2'
services:
    server-app:
        image: server
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://server-postgresql:5432/server
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    server-postgresql:
        extends:
            file: postgresql.yml
            service: server-postgresql
