version: '2'
services:
    server-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/server/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=server
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
